
export const SEARCH_USER_BY_AGE_INIT = 'SEARCH_USER_BY_AGE_INIT';
export const SEARCH_USER_BY_AGE_SUCCESS = 'SEARCH_USER_BY_AGE_SUCCESS';
export const SEARCH_USER_BY_AGE_ERROR = 'SEARCH_USER_BY_AGE_ERROR';


export const GET_ALL_REPOS_INIT = 'GET_ALL_REPOS_INIT';
export const GET_ALL_REPOS_FINISHED = 'GET_ALL_REPOS_FINISHED';
export const GET_ALL_REPOS_ERROR = 'GET_ALL_REPOS_ERROR';

export const FETCH_TAGS_LIST_INIT = 'FETCH_TAGS_LIST_INIT';
export const FETCH_TAGS_LIST_FINISHED = 'FETCH_TAGS_LIST_FINISHED';
export const FETCH_TAGS_LIST_ERROR = 'FETCH_TAGS_LIST_ERROR';

export const SORT_TAGS_LIST = 'SORT_TAGS_LIST';

export const ADD_NEW_TAG_INIT = 'ADD_NEW_TAG_INIT';
export const ADD_NEW_TAG_FINISHED = 'ADD_NEW_TAG_FINISHED';
export const ADD_NEW_TAG_ERROR = 'ADD_NEW_TAG_ERROR';

export const FETCH_REPO_DETAILS_INIT = 'FETCH_REPO_DETAILS_INIT';
export const FETCH_REPO_DETAILS_FINISHED = 'FETCH_REPO_DETAILS_FINISHED';
export const FETCH_REPO_DETAILS_ERROR = 'FETCH_REPO_DETAILS_ERROR';

export const SAVE_REPO_TEXT_INIT = 'SAVE_REPO_TEXT_INIT';
export const SAVE_REPO_TEXT_FINISHED = 'SAVE_REPO_TEXT_FINISHED';
export const SAVE_REPO_TEXT_ERROR = 'SAVE_REPO_TEXT_ERROR';

export const SAVE_REPO_TAGS_INIT = 'SAVE_REPO_TAGS_INIT';
export const SAVE_REPO_TAGS_FINISHED = 'SAVE_REPO_TAGS_FINISHED';
export const SAVE_REPO_TAGS_ERROR = 'SAVE_REPO_TAGS_FINISHED';
