
export const SEARCH_USER_BY_AGE_INIT = 'SEARCH_USER_BY_AGE_INIT';
export const SEARCH_USER_BY_AGE_SUCCESS = 'SEARCH_USER_BY_AGE_SUCCESS';
export const SEARCH_USER_BY_AGE_ERROR = 'SEARCH_USER_BY_AGE_ERROR';


export const GET_ALL_REPOS = 'GET_ALL_REPOS';
export const FETCH_REPO_LIST = 'FETCH_REPO_LIST';
export const FETCH_TAGS_LIST = 'FETCH_TAGS_LIST';

export const ADD_NEW_TAG = 'ADD_NEW_TAG';

export const FETCH_REPO_DETAILS = 'FETCH_REPO_DETAILS';

export const SAVE_REPO_TEXT = 'SAVE_REPO_TEXT';
export const SAVE_REPO_TAGS = 'SAVE_REPO_TAGS';
